sonar.projectKey=Habitus
sonar.projectName=Habitus
sonar.sourceEncoding=UTF-8

# Le decimos a Sonar que el código a escanear está dentro de tu módulo
sonar.sources=composeApp/src

# EXCLUSIONES: Ignorar UI, Modelos, Cliente de Red, Main y Sesión
sonar.coverage.exclusions=**/ui/**/*, **/*Screen.kt, **/viewmodel/**/*, **/ApiClient.kt